import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // *Client.ts files are generated by `stellar contract bindings typescript`
  // (regen: `npm run generate` in packages/*-client) — don't lint generator output.
  globalIgnores(['dist', 'src/lib/treasuryClient.ts', 'src/lib/registryClient.ts']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
    rules: {
      // Deferred (2026-07-09): the treasury/session views chain several loads through
      // effects that setState synchronously; untangling them is a behaviour-risky refactor
      // tracked in tasks/todo.md. Downgraded to warn so lint gates real errors without
      // hiding these — restore to error once the effect refactor lands.
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/refs': 'warn',
    },
  },
])
